### ISSUE TITLE
Authenticator key.

### ISSUE THREAD

**Issue by ratneshnavlakhe** [detj/moor#2]
There is some issue with authentication for username and password
Please correct me if I am wrong.

https://cloudup.com/c32ccGSTv8d

**Comment by detj** [comment]
@ratneshnavlakhe Yes, this happens when the VPN server disconnects the connection/tunnel gets destroyed. One solution I'm thinking is to eliminate Tunnelblick as a dependency & move to `openvpn` instead. Doing that would also help us to do more useful stuff like auto-reconnecting on disconnection etc.

**Comment by detj** [comment]
@ratneshnavlakhe Download `v0.0.2` and try. Let me know if you face any other connection issue.

```
npm update -g moor
```
